### ISSUE TITLE
KeyError: 'access_token' on startup

### ISSUE THREAD

**Issue by emdete** [tulir/mautrix-signal#101]
On startup i see the following message:

```
Error while syncing own puppet
Traceback (most recent call last):
File "lib/python3.9/site-packages/mautrix_signal/user.py", line 136, in sync await self._sync_puppet()
File "lib/python3.9/site-packages/mautrix_signal/user.py", line 132, in _sync_puppet await puppet.switch_mxid(access_token="auto", mxid=self.mxid)
File "lib/python3.9/site-packages/mautrix/bridge/custom_puppet.py", line 172, in switch_mxid access_token = await self._login_with_shared_secret(mxid)
File "lib/python3.9/site-packages/mautrix/bridge/custom_puppet.py", line 157, in _login_with_shared_secret return data["access_token"]
KeyError: 'access_token'
```

It's a pip installation "mautrix-signal 0.1.1".

**Comment by tulir** [comment]
That just means the login shared secret is wrong, shouldn't break anything else

**Comment by emdete** [comment]
which login? why does it fail? i just started the bridge. is it the login towards the homeserver?

if you say "shouldn't break anything else" it means something broke but what? was it expected to succeed? if not, why is it logged or even done anyway?

if its not a bug the code should check if the key is in the dict before accessing it and acting accordingly, do you agree?

**Comment by tulir** [comment]
The [double puppeting](https://docs.mau.fi/bridges/general/double-puppeting.html) auto-login fails because the secret you entered in `login_shared_secret_map` wasn't accepted by your homeserver. It's expected to work if you enter a secret there (auto-login won't even be attempted if you don't enter anything). Could probably catch the error and log a warning about the secret being misconfigured, but it doesn't break anything (other than the auto-login itself), so it's not a big deal

**Comment by emdete** [comment]
Thank you for explaining and pointing me to the right place. Could the logging be enhanced to give this information to an average user like me?
