### ISSUE TITLE
Groups v2 Support

### ISSUE THREAD

**Issue by markusressel** [tulir/mautrix-signal#17]
Basic support for v2 groups has been merged into [signald](https://gitlab.com/thefinn93/signald/-/issues/34) recently. It seems like some modifications are necessary to use it in clients though. Would be great to see this come to life :smiley:

**Comment by tulir** [comment]
Initial groups v2 support added in bd3fa8fcef4b9abea265e45519f13a7822e6753b

**Comment by markusressel** [comment]
@tulir Wow, that was quick!
Sadly I am getting an error though (actually two, but I think the contact sync one is unrelated to groups v2):

```
[2020-11-25 21:11:09,238] [ERROR@mau.user.@markus:redacted] Failed to sync contact Address(number='+49redacted', uuid=UUID('redacted'))
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'name'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_signal/user.py", line 149, in _sync
    await self._sync_contact(contact, create_contact_portal)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/user.py", line 117, in _sync_contact
    profile = await self.bridge.signal.get_profile(self.username, contact.address)
  File "/opt/mautrix-signal/mausignald/signald.py", line 162, in get_profile
    return Profile.deserialize(resp)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key name in Profile


[2020-11-25 21:11:09,291] [ERROR@mau.user.@markus:redacted] Error while syncing
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 3 required positional arguments: 'pending_members', 'requesting_members', and 'timer'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_signal/user.py", line 109, in sync
    await self._sync()
  File "/usr/lib/python3.8/site-packages/mautrix_signal/user.py", line 153, in _sync
    for group in await self.bridge.signal.list_groups(self.username):
  File "/opt/mautrix-signal/mausignald/signald.py", line 152, in list_groups
    + [GroupV2.deserialize(group) for group in resp["groupsv2"]])
  File "/opt/mautrix-signal/mausignald/signald.py", line 152, in <listcomp>
    + [GroupV2.deserialize(group) for group in resp["groupsv2"]])
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key master_key in GroupV2
```

Thx for your work, I hope this helps!
