### ISSUE TITLE
Failing to recieve messages (missing 1 required positional argument: 'source_device').

### ISSUE THREAD

**Issue by zsinskri** [tulir/mautrix-signal#19]
I have a mautrix-signal 0.1.0b2+dev.unknown (installed with pip from this repos master into a venv) instance with signald 0.10.0+git2020-12-10r09ed90b0.59 (from https://updates.signald.org) and matrix-synapse-py3 1.24.0+buster1 (from https://packages.matrix.org/debian) on Debian GNU/Linux 10.

This setup (with older versions) used to able to send and receive messages. Sending message still works fine.
When receiving a message, no message shows up on the matrix side and the following is logged:

```
[2020-12-10 20:49:51,081] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'source_device'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 123, in _dict_to_attrs
    f"Missing value for required key {field.name} in {attrs_type.__name__}") from e
mautrix.types.util.serializable.SerializerError: Missing value for required key timestamp_iso in Message
[2020-12-10 20:49:52,519] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'source_device'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 123, in _dict_to_attrs
    f"Missing value for required key {field.name} in {attrs_type.__name__}") from e
mautrix.types.util.serializable.SerializerError: Missing value for required key timestamp_iso in Message
[2020-12-10 20:49:56,550] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 3 required positional arguments: 'server_timestamp', 'has_content', and 'is_unidentified_sender'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 123, in _dict_to_attrs
    f"Missing value for required key {field.name} in {attrs_type.__name__}") from e
mautrix.types.util.serializable.SerializerError: Missing value for required key timestamp_iso in Message
[2020-12-10 20:49:57,087] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'source_device'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/matrix-service/mautrix-signal/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 123, in _dict_to_attrs
    f"Missing value for required key {field.name} in {attrs_type.__name__}") from e
mautrix.types.util.serializable.SerializerError: Missing value for required key timestamp_iso in Message
```

signald does not log any errors:
```
Dec 10 20:27:50 agon.one signald[24096]: 20:27:50.829 [main] INFO  io.finn.signald.Main - Binding to socket /var/run/signald/signald.sock
Dec 10 20:27:50 agon.one signald[24096]: 20:27:50.914 [main] INFO  io.finn.signald.Main - Started signald 0.10.0+git2020-12-10r09ed90b0.59
Dec 10 20:28:14 agon.one signald[24096]: 20:28:14.863 [socketlistener] INFO  io.finn.signald.SocketHandler - Client connected
Dec 10 20:28:15 agon.one signald[24096]: 20:28:15.192 [socketlistener] INFO  manager-************97 - Creating new manager for ************97 (stored at /var/lib/signald)
Dec 10 20:28:19 agon.one signald[24096]: 20:28:19.680 [socketlistener] INFO  manager - Created a manager for ************97
```

I was able to consistently reproduce this issue with similar error messages every time. I have only a single room bridged to Signal, so this might be specific to this chat (though I have no specific reason to believe it is).

**Comment by zsinskri** [comment]
This has been fixed in commit ecbdc0bd.
