### ISSUE TITLE
Periodically run into a AttributeError exception and no longer process messages

### ISSUE THREAD

**Issue by dubwoc** [tulir/mautrix-signal#24]
Periodically while running mautrix-signal I get into a state where likely an event results in something unexpected and it hangs the process resulting in chat messages no longer being processed in either direction.

```
[2020-12-19 05:46:13,540] [INFO@aiohttp.access] 127.0.0.1 [19/Dec/2020:05:46:13 +0000] "PUT /transactions/354?access_token=<redacted> HTTP/1.1" 200 158 "-" "Synapse/1.21.2"
[2020-12-19 05:46:14,257] [DEBUG@mau.portal.HgKa0aRvDnJH2Qv7cC11H3M/+iWXyUgafvbitfb18Uk=] Handled Matrix message $pjX-_STQkNdsfadfp4cBqk2rt4ydTm8sC_KfA6w8eXbLtpctA -> 1608356773537
[2020-12-19 05:47:22,651] [DEBUG@mausignald] Reader disconnected
[2020-12-19 05:47:40,060] [DEBUG@mau.init] Interrupt received, stopping...
[2020-12-19 05:47:40,061] [DEBUG@mau.as] Stopping appservice web server
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/__main__.py", line 107, in <module>
    SignalBridge().run()
  File "/usr/lib/python3.8/site-packages/mautrix/util/program.py", line 84, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/mautrix/util/program.py", line 203, in _run
    self.loop.run_until_complete(self.stop())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 156, in stop
    await super().stop()
  File "/usr/lib/python3.8/site-packages/mautrix/util/program.py", line 228, in stop
    await asyncio.gather(*(self.shutdown_actions or []))
  File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 145, in stop
    await self.disconnect()
  File "/opt/mautrix-signal/mausignald/rpc.py", line 48, in disconnect
    self._writer.write_eof()
AttributeError: 'NoneType' object has no attribute 'write_eof'
```

I am running the latest mautrix-signal container as of yesterday where in the container it has this version of the python module: 
mautrix_signal-0.1.0b2+dev.29a5f91b.dist-info/.

Ideally at the very least when we run into this condition it wouldn't hang the process. 

Let me know what other information I can provide and If I find out more i'll update the bug accordingly. 

Thank you for mautrix-signal as well as the other ones it is much appreciated.

**Comment by dubwoc** [comment]
The above may actually be a symptom of the problem rather than me capturing the actual problem. I can reproduce the above stacktrace by killing signald and then restarting the container for mautrix-signal. 

However, while watching this I ran into another exception while trying to reproduce this,  If I determine it is unrelated I may open a new bug:

```
[2020-12-20 19:50:57,911] [DEBUG@mau.portal.2xWrTwylUO324nsx2zqfqA==] Handled Signal message 1608493857202 -> $QrN7jl24BPoCiIB66q_Lt_BjW8X4iXQKDwwwqvSRIG4
[2020-12-20 19:50:57,949] [INFO@aiohttp.access] 127.0.0.1 [20/Dec/2020:19:50:57 +0000] "PUT /transactions/637?access_token=<redacted> HTTP/1.1" 200 158 "-" "Synapse/1.21.2"
[2020-12-20 19:51:00,146] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'expiration_start_timestamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-signal/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/mautrix-signal/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 112, in _dict_to_attrs
    new_items[name] = _try_deserialize(field.type, value, field.default,
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 133, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 175, in _deserialize
    return _deserialize(cls.__args__[0], value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 170, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 112, in _dict_to_attrs
    new_items[name] = _try_deserialize(field.type, value, field.default,
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 133, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 175, in _deserialize
    return _deserialize(cls.__args__[0], value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 170, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key expiration_start_timestamp in SentSyncMessage
```

**Comment by dubwoc** [comment]
Actually now that I see #18 I think I'll close this and re-open a new bug if I see it again as #18 captures the initial error.
