### ISSUE TITLE
Missing value for required key expiration_start_timestamp in SentSyncMessage

### ISSUE THREAD

**Issue by dubwoc** [tulir/mautrix-signal#25]
I ran into the exception attached below while debugging another issue, the bridge continued to work as expected but I assume the event was dropped. 

```
[2020-12-20 19:50:57,911] [DEBUG@mau.portal.2xWrTwylUO324nsx2zqfqA==] Handled Signal message 1608493857202 -> $QrN7jl24BPoCiIB66q_Lt_BjW8X4iXQKDwwwqvSRIG4
[2020-12-20 19:50:57,949] [INFO@aiohttp.access] 127.0.0.1 [20/Dec/2020:19:50:57 +0000] "PUT /transactions/637?access_token=<redacted> HTTP/1.1" 200 158 "-" "Synapse/1.21.2"
[2020-12-20 19:51:00,146] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'expiration_start_timestamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-signal/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/mautrix-signal/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 112, in _dict_to_attrs
    new_items[name] = _try_deserialize(field.type, value, field.default,
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 133, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 175, in _deserialize
    return _deserialize(cls.__args__[0], value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 170, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 112, in _dict_to_attrs
    new_items[name] = _try_deserialize(field.type, value, field.default,
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 133, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 175, in _deserialize
    return _deserialize(cls.__args__[0], value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 170, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key expiration_start_timestamp in SentSyncMessage
```

**Comment by tulir** [comment]
Was fixed in 99f07bf891ff7ba4d490cf1a505a9ab41605a921
