### ISSUE TITLE
mautrix.types.util.serializable.SerializerError: Missing value for required key revision in GroupV2ID

### ISSUE THREAD

**Issue by dubwoc** [tulir/mautrix-signal#26]
Ran into this with a group chat:

```
[2020-12-20 21:08:30,196] [ERROR@mausignald] Exception in RPC event handler
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-signal/mausignald/rpc.py", line 68, in _run_rpc_handler
    await handler(req)
  File "/opt/mautrix-signal/mausignald/signald.py", line 58, in _parse_message
    event = event_class.deserialize(event_data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 112, in _dict_to_attrs
    new_items[name] = _try_deserialize(field.type, value, field.default,
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 133, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 175, in _deserialize
    return _deserialize(cls.__args__[0], value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 170, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 112, in _dict_to_attrs
    new_items[name] = _try_deserialize(field.type, value, field.default,
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 133, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 175, in _deserialize
    return _deserialize(cls.__args__[0], value, default)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 170, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key revision in GroupV2ID
```

**Comment by a000a** [comment]
me, too
even after reinstalling the bridge using dev setup
