### ISSUE TITLE
Friendlier error message when signald is not running

### ISSUE THREAD

**Issue by Evidlo** [tulir/mautrix-signal#27]
When signald is not running, we get the rather unhelpful message below.

```
Traceback (most recent call last):
  File "/home/evan/resources/venv3/lib/python3.7/site-packages/mautrix/util/program.py", line 190, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/evan/resources/venv3/lib/python3.7/site-packages/mautrix_signal/__main__.py", line 76, in start
    await super().start()
  File "/home/evan/resources/venv3/lib/python3.7/site-packages/mautrix/bridge/bridge.py", line 151, in start
    await super().start()
  File "/home/evan/resources/venv3/lib/python3.7/site-packages/mautrix/util/program.py", line 213, in start
    await asyncio.gather(*(self.startup_actions or []))
  File "/home/evan/resources/venv3/lib/python3.7/site-packages/mautrix_signal/signal.py", line 138, in start
    await self.connect()
  File "/home/evan/resources/venv3/lib/python3.7/site-packages/mausignald/rpc.py", line 44, in connect
    self._reader, self._writer = await asyncio.open_unix_connection(self.socket_path)
  File "/usr/lib/python3.7/asyncio/streams.py", line 128, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by satwell** [comment]
This should be fixed by #20.  When the socket doesn't exist you should now see repeated messages like this:

```
[2021-02-05 14:43:11,640] [ERROR@mausignald] Connection to /signald/signald.sock failed: [Errno 2] No such file or directory
```
