### ISSUE TITLE
AttributeError: type object 'BasePortal' has no attribute 'bridge'

### ISSUE THREAD

**Issue by Yajo** [tulir/mautrix-signal#35]
After `clean-confirm` for some rooms:

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/clean_rooms.py", line 184, in execute_room_cleanup
    await BasePortal.cleanup_room(evt.az.intent, room, "Room deleted")
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/portal.py", line 111, in cleanup_room
    puppet = await cls.bridge.get_puppet(user_id, create=False)
AttributeError: type object 'BasePortal' has no attribute 'bridge'
```

**Comment by tulir** [comment]
Are you using an up-to-date version of the bridge?

**Comment by Yajo** [comment]
I'm using mautrix-signal 0.1.0b2+dev.0defb3f7

**Comment by joao-p-marques** [comment]
Thanks @tulir! Is this fix already available as a release?

**Comment by Yajo** [comment]
I think this still has no release...

**Comment by joao-p-marques** [comment]
Yes, but yet I don't see any release here on Github. I think this uses an external CI from https://mau.dev/tulir/mautrix-signal.
