### ISSUE TITLE
Fails registering

### ISSUE THREAD

**Issue by Yajo** [tulir/mautrix-signal#39]
Here you see the conversation:

![imagen](https://user-images.githubusercontent.com/973709/104770347-59d0bf00-5768-11eb-893f-e4105dad5b69.png)

Notice that I was already registered on signal in my phone, but I'd love to be able to uninstall it from there and keep only the matrix version.

Full trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 93, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 98, in verify
    resp = await self.request("verify", "verification_succeeded", username=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 157, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 154, in _raw_request
    return await future
mausignald.errors.UnexpectedError: java.net.SocketTimeoutException: timeout
```

Version: mautrix-signal 0.1.0b2+dev.0defb3f7

**Comment by felbinger** [comment]
Got basicly the same error, but the stacktrace is a bit diffrent. I thought it might be usedful to solve the problem so I added it below.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 84, in register
    username = await evt.bridge.signal.register(phone, voice=voice)
  File "/opt/mautrix-signal/mausignald/signald.py", line 104, in register
    resp = await self.request("register", "verification_required", username=phone,
  File "/opt/mautrix-signal/mausignald/rpc.py", line 200, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 197, in _raw_request
    return await future
mausignald.errors.UnexpectedError: Unexpected error with no message
```

**Comment by foux** [comment]
I've got the same erros as @felbinger, execpt that it is not at the same moment than @Yajo : it happens as soon as I entered the `register` command, I don't receive the SMS. I suppose it's the same for you @felbinger. Should we create a new issue for this one?

**Comment by thedanbob** [comment]
Just ran across the same thing. I checked the logs and found more details:

```
matrix-mautrix-signal-daemon[27677]: 19:16:29.383 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
matrix-mautrix-signal-daemon[27677]: org.whispersystems.signalservice.api.push.exceptions.CaptchaRequiredException: null
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$1.handle(PushServiceSocket.java:267) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1433) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1350) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestSmsVerificationCode(PushServiceSocket.java:263) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:236) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
matrix-mautrix-signal-daemon[27677]:         at io.finn.signald.Manager.register(Manager.java:317) ~[signald.jar:unspecified]
matrix-mautrix-signal-daemon[27677]:         at io.finn.signald.SocketHandler.register(SocketHandler.java:396) ~[signald.jar:unspecified]
matrix-mautrix-signal-daemon[27677]:         at io.finn.signald.SocketHandler.handleRequest(SocketHandler.java:192) [signald.jar:unspecified]
matrix-mautrix-signal-daemon[27677]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:134) [signald.jar:unspecified]
matrix-mautrix-signal-daemon[27677]:         at java.lang.Thread.run(Unknown Source) [?:?]
matrix-mautrix-signal[27822]: [2021-02-03 19:16:29,389] [ERROR@mau.commands] Unhandled error while handling command register [REDACTED] from [REDACTED] (ref: 1612379147)
matrix-mautrix-signal[27822]: Traceback (most recent call last):
matrix-mautrix-signal[27822]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
matrix-mautrix-signal[27822]:     await self._run_handler(handler, evt)
matrix-mautrix-signal[27822]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
matrix-mautrix-signal[27822]:     return await self._handler(evt)
matrix-mautrix-signal[27822]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 84, in register
matrix-mautrix-signal[27822]:     username = await evt.bridge.signal.register(phone, voice=voice)
matrix-mautrix-signal[27822]:   File "/opt/mautrix-signal/mausignald/signald.py", line 104, in register
matrix-mautrix-signal[27822]:     resp = await self.request("register", "verification_required", username=phone,
matrix-mautrix-signal[27822]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 200, in request
matrix-mautrix-signal[27822]:     resp_type, resp_data = await self._raw_request(command, **data)
matrix-mautrix-signal[27822]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 197, in _raw_request
matrix-mautrix-signal[27822]:     return await future
matrix-mautrix-signal[27822]: mausignald.errors.UnexpectedError: Unexpected error with no message
```
Going by that second line, it looks like the crash is caused by Signal requiring a captcha.

**Comment by elmehalawi** [comment]
@thedanbob How are you getting those logs? I tried getting those logs with:

```
systemctl status -f matrix-mautrix-signal
# and:
systemctl status -f matrix-mautrix-signal-daemon
```

And neither show anything when I run register.

**Comment by thedanbob** [comment]
I’m running them in docker via [this project](https://github.com/spantaleev/matrix-docker-ansible-deploy) and they just show up in the system logs. Maybe you need to change the logging level? https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2

**Comment by elmehalawi** [comment]
I'm seeing `INFO` entries in the logs, so I must be running into something else. Thanks though!

**Comment by foux** [comment]
@tulir I think we've got two different issues here. Do you want us to split them?

**Comment by jannis3005** [comment]
Im having the same issue when registering, also getting the CaptchaRequiredException

**Comment by corrupt3k** [comment]
I also have this issue.

`Feb 09 11:25:04 element matrix-mautrix-signal[12137]: Traceback (most recent call last):
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:     await self._run_handler(handler, evt)
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:     return await self._handler(evt)
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 84, in register
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:     username = await evt.bridge.signal.register(phone, voice=voice)
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:   File "/opt/mautrix-signal/mausignald/signald.py", line 104, in register
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:     resp = await self.request("register", "verification_required", username=phone,
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 200, in request
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:     resp_type, resp_data = await self._raw_request(command, **data)
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 197, in _raw_request
Feb 09 11:25:04 element matrix-mautrix-signal[12137]:     return await future
Feb 09 11:25:04 element matrix-mautrix-signal[12137]: mausignald.errors.UnexpectedError: Unexpected error with no message
`

**Comment by tijder** [comment]
You can temporary fix this by solving the captcha here: https://signalcaptchas.org/registration/generate.html (Firefox didn't work for me, I had to use chromium). The redirect url, that shown in the network tab (f12) needs to be filled on this line: https://github.com/tulir/mautrix-signal/blob/5fa2c227ea2f383388099cacd0ba9812be872ff1/mausignald/signald.py#

```Python
resp = await self.request("register", "verification_required", username=phone,
                                  voice=voice, captcha="CAPTCHA")
```

Then run the register command once more. 

[Signald wiki about Captchas](https://gitlab.com/signald/signald/-/wikis/Captchas)

**Comment by thedanbob** [comment]
For anyone running this in docker (e.g. matrix-docker-ansible-deploy), here's one way to do this:

1. Copy signald.py from github or the docker container to somewhere on the server: `docker exec <container ID> bash -c 'cat mausignald/signald.py' > signald.py`
2. Generate a captcha link and edit the file as mentioned, without the `signalcaptcha://` prefix
3. Add a bind mount for that file to the docker command: `-v "<dir>/signald.py:/opt/mautrix-signal/mausignald/signald.py"`. If you're running matrix-docker-ansible-deploy, the service file to edit can be found at `/etc/systemd/system/matrix-mautrix-signal.service`.
4. Restart the `matrix-mautrix-signal` service / recreate the container
5. Register
6. Remove the bind mount and restart the container again

**Comment by foux** [comment]
Thanks you both, that was really helpfull!

Unfortunately it got me only one step further : after inputing the code received by SMS, I got the following error : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 97, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 110, in verify
    resp = await self.request("verify", "verification_succeeded", username=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 205, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 202, in _raw_request
    return await future
mausignald.errors.UnexpectedError: Bad response: 400 
```

**Comment by pcolusso** [comment]
Also running into this, instead of modifying the code you can send raw commands to signald, using raw register `{ "type": "register", "username": "", "captcha": "" }`, then signald responds with `Got reply verification_required:`.

Did receive the SMS verify, `raw verify {"type": "verify", "username": "", "code": "" }` but receive the same Bad Response 400, but this looks like it's coming from signald; log below

```
01:13:29.451 [socketlistener] INFO  io.finn.signald.SocketHandler - Submitting verification code [REDACTED] for number [REDACTED]
01:13:29.661 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 400
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1477) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1435) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1338) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:314) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccountWithCode(SignalServiceAccountManager.java:276) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_17.jar:?]
	at io.finn.signald.Manager.verifyAccount(Manager.java:407) ~[signald.jar:unspecified]
	at io.finn.signald.SocketHandler.verify(SocketHandler.java:407) ~[signald.jar:unspecified]
	at io.finn.signald.SocketHandler.handleRequest(SocketHandler.java:193) [signald.jar:unspecified]
	at io.finn.signald.SocketHandler.run(SocketHandler.java:132) [signald.jar:unspecified]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by abliss** [comment]
I was able to get registration to complete using the `raw register` and `raw verify` commands, but it doesn't seem to have linked my matrix user to the account, so I still can't use it (the bot says 'you must be logged in'). I would suggest thedanbob's method instead.
