### ISSUE TITLE
Fail to link device : `mausignald.errors.UnexpectedError: Could not initialize class org.signal.zkgroup.internal.Native`

### ISSUE THREAD

**Issue by altor** [tulir/mautrix-signal#54]
Hi

I'm trying to link the matrix bridge with my signal account but it raise an `mausignald.errors.UnexpectedError: Could not initialize class org.signal.zkgroup.internal.Native` My primary device is a linux laptop that i registered with [`signal-cli`](https://github.com/AsamK/signal-cli)

Here is the step i followed : 

- type `link` in the bridge bot chat
- get data from the qr-code
- on my primary device use the commande `signal-cli -u PHONE_NUMBER addDevice --uri DATA_FROM_QRCODE` the command is executed without error

after that the bot send me the message **Unhandled error while handling command:** with the following trace stack : 
```
Traceback (most recent call last):
  File "/opt/synapse/mautrix-signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 399, in handle
    await self._run_handler(handler, evt)
  File "/opt/synapse/mautrix-signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 286, in __call__
    return await self._handler(evt)
  File "/opt/synapse/mautrix-signal/lib/python3.7/site-packages/mautrix_signal/commands/auth.py", line 58, in link
    account = await evt.bridge.signal.link(callback, device_name=device_name)
  File "/opt/synapse/mautrix-signal/lib/python3.7/site-packages/mausignald/signald.py", line 76, in link
    resp_type, resp = await self._wait_response(req_id)
mausignald.errors.UnexpectedError: Could not initialize class org.signal.zkgroup.internal.Native
```

Is it a bug from the bridge or is it a problem with the way i use to link to my account ?
Thanks for your work !

**Comment by thefinn93** [comment]
This is a signald issue, please file it here: https://gitlab.com/signald/signald/-/issues/new

**Comment by altor** [comment]
Ok thanks !
