### ISSUE TITLE
Unable to (re) link (UserAlreadyExists: null)

### ISSUE THREAD

**Issue by podiki** [tulir/mautrix-signal#69]
Occurring with signald v0.12, I believe it was after updating with the changes to using v1 protocol for linking 8738afa35a8bfc694e9e927acaf5eb9f7eae9e46. (Though I also moved from a signald git package to latest stable release, I don't think that would come into play here since those signald changes for the protocol were many months ago...?)

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 62, in link
    sess = await evt.bridge.signal.start_link()
  File "/usr/lib/python3.9/site-packages/mausignald/signald.py", line 113, in start_link
    return LinkSession.deserialize(await self.request_v1("generate_linking_uri"))
  File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 213, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 204, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 201, in _raw_request
    return await future
mausignald.errors.InvalidRequest: Unknown request type: generate_linking_uri
```

**Comment by thefinn93** [comment]
`generate_linking_uri` was added [on February 6](https://gitlab.com/signald/signald/-/commit/7331b94b02efbe21be08d4f88bad083afd6da496), but 0.12.0 was released [on January 29th](https://gitlab.com/signald/signald/-/releases/0.12.0).

**Comment by podiki** [comment]
Ah, you are right, I thought that was part of earlier protocol changes in signald and missed the commit. So I had gone back to the last release of signald as I wasn't sure what version the bridge needs (is undocumented?) and was trying to fix an error there I had lost connection and can no longer log back in due to the following errors. After upgrading signald to the latest git version I'm getting the same errors below (tried wiping the signald db but that didn't change anything):

mautrix-signal:
```
Mar 18 10:39:53  python[22146]: [2021-03-18 10:39:53,696] [ERROR@mausignald] Failed to handle incoming request {"id":"HIDDEN","type":"finish_link","error":{},"error_type":"RequestProcessingError"}
Mar 18 10:39:53  python[22146]: Traceback (most recent call last):
Mar 18 10:39:53  python[22146]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 160, in _read_loop
Mar 18 10:39:53  python[22146]:     await self._handle_incoming_line(line_str)
Mar 18 10:39:53  python[22146]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 141, in _handle_incoming_line
Mar 18 10:39:53  python[22146]:     self._run_response_handlers(UUID(req_id), req_type, req)
Mar 18 10:39:53  python[22146]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 119, in _run_response_handlers
Mar 18 10:39:53  python[22146]:     waiter.set_exception(make_response_error(req["error"]))
Mar 18 10:39:53  python[22146]:   File "/usr/lib/python3.9/site-packages/mausignald/errors.py", line 64, in make_response_error
Mar 18 10:39:53  python[22146]:     return response_error_types.get(data["type"], ResponseError)(data)
Mar 18 10:39:53  python[22146]: KeyError: 'type'
```

signald:
```
Mar 18 10:39:53  signald[22106]: 10:39:53.696 [socketlistener] ERROR finish_link - error while handling request
Mar 18 10:39:53  signald[22106]: org.asamk.signal.UserAlreadyExists: null
Mar 18 10:39:53  signald[22106]:         at io.finn.signald.ProvisioningManager.finishDeviceLink(ProvisioningManager.java:88) ~[signald.jar:unspecified]
Mar 18 10:39:53  signald[22106]:         at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:48) ~[signald.jar:unspecified]
Mar 18 10:39:53  signald[22106]:         at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:36) ~[signald.jar:unspecified]
Mar 18 10:39:53  signald[22106]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:150) [signald.jar:unspecified]
Mar 18 10:39:53  signald[22106]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
Mar 18 10:39:53  signald[22106]:         at java.lang.Thread.run(Thread.java:832) [?:?]
```

Any idea why `UserAlreadyExists` error is coming up all of a sudden? Everything was working well, so either something happened on Signal's end or something got corrupted (can't say their official client is reliable either on desktop), or it was from updating the bridge (previously up to commits on Feb 28th, so I was thinking it was the v1 protocol changes...)

**Comment by thefinn93** [comment]
you have to remove the old account from signald before you can re-link. If you don't have any other accounts, the easiest way to proceed is probably to delete signald's state files and try again. Depending on how you're running signald, those might be in `~/.config/signald` or `/var/lib/signald` (in which case you'll want to be careful not to delete the `lib` or `bin` folders). Alternatively, download [signaldctl](https://gitlab.com/signald/signald-go/-/blob/main/cmd/signaldctl/README.md) and run `signaldctl account delete <phone number>`, which will cleanly remove just that account from signald.

**Comment by podiki** [comment]
Yes, I did stop signald, and just tried again with the same results (just removing the .db). Something weird was going on which prompted my mucking about, which was that suddenly contact names became something random looking, and I think messages were no longer syncing. That prompted my trying to logout and back in (and then trying different version of signald, etc.). Looking at the logs the bridge was constantly (every second or more) dis/reconnecting. Wish I could be more helpful on that front, maybe a bad connection, update or data gone bad (I had some unrelated, I think, other issues causing restarts before that)...?

I can just wipe the bridge and signald and start over, though that's not optimal. What else besides signald's db should I look into?

(And thanks for your patience and help, before this the bridge and signald were working great and easy to set up!)

**Comment by thefinn93** [comment]
next to `signald.db` is a folder called `data`, you need to delete it too. signald is currently in the process of moving how it's data is stored.

As for the garbled contact names, that may a bug in signald, someone reported something similar on IRC earlier today and I haven't had a chance to look. If you experience it after re-linking please file an issue on signald so I can look at it further.

**Comment by podiki** [comment]
Hmm...is there another data source somewhere? When signald starts up it still has an account it seems....?

```
Mar 19 00:25:10  signald[28480]: 00:25:10.446 [main] INFO  io.finn.signald.Main - applied migration create message queue (1) in 14 ms
Mar 19 00:25:10  signald[28480]: 00:25:10.455 [main] INFO  io.finn.signald.Main - applied migration create core account tables (2) in 10 ms
Mar 19 00:25:10  signald[28480]: 00:25:10.937 [main] INFO  io.finn.signald.db.AccountsTable - migrating account if needed: ************/************************************
Mar 19 00:25:10  signald[28480]: 00:25:10.997 [main] INFO  io.finn.signald.Main - Binding to socket /var/run/signald/signald.sock
```

And then when linking it still fails, with different error (and then same error as before if I try again):

```
Mar 19 00:26:22  python[28528]: [2021-03-19 00:26:22,681] [ERROR@mausignald] Failed to handle incoming request {"id":"(redacted)","type":"finish_link","error":{},"error_type":"RequestProcessingError"}
Mar 19 00:26:22  python[28528]: Traceback (most recent call last):
Mar 19 00:26:22  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 160, in _read_loop
Mar 19 00:26:22  python[28528]:     await self._handle_incoming_line(line_str)
Mar 19 00:26:22  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 141, in _handle_incoming_line
Mar 19 00:26:22  python[28528]:     self._run_response_handlers(UUID(req_id), req_type, req)
Mar 19 00:26:22  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 119, in _run_response_handlers
Mar 19 00:26:22  python[28528]:     waiter.set_exception(make_response_error(req["error"]))
Mar 19 00:26:22  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/errors.py", line 64, in make_response_error
Mar 19 00:26:22  python[28528]:     return response_error_types.get(data["type"], ResponseError)(data)
Mar 19 00:26:22  python[28528]: KeyError: 'type'

```

```
Mar 19 00:26:22  signald[28480]: 00:26:22.680 [socketlistener] ERROR finish_link - error while handling request
Mar 19 00:26:22  signald[28480]: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1459) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1444) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1386) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.getAvailablePreKeys(PushServiceSocket.java:486) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at org.whispersystems.signalservice.api.SignalServiceAccountManager.getPreKeysCount(SignalServiceAccountManager.java:339) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.jobs.RefreshPreKeysJob.run(RefreshPreKeysJob.java:44) ~[signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.jobs.RefreshPreKeysJob.runIfNeeded(RefreshPreKeysJob.java:54) ~[signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.Manager.get(Manager.java:165) ~[signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.Manager.get(Manager.java:182) ~[signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:49) ~[signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.clientprotocol.v1.FinishLinkRequest.run(FinishLinkRequest.java:36) ~[signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:150) [signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
Mar 19 00:26:22  signald[28480]:         at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by thefinn93** [comment]
the database and the `data/` folder are the places signald stores it's data. Perhaps it would be easier to download [signaldctl](https://gitlab.com/signald/signald-go/-/blob/main/cmd/signaldctl/README.md) and run `signaldctl account delete <phone number>`.

I'm not sure how you got into the state that caused that exception you posted, it seems like it completed linking successfully, but somehow still got authorization failed. That's probably worth opening a bug on signald about.

**Comment by thefinn93** [comment]
I was able to replicate the garbled profile name issue and filed https://gitlab.com/signald/signald/-/issues/145

**Comment by podiki** [comment]
Thanks, using signaldctl does delete the account and allow it to link. But then it fails on a `get_profile` (I also tried sending 'sync'). Hopefully I redacted just enough, but on the bridge side it has different `id`s

```
Mar 19 00:49:09  python[28528]: [2021-03-19 00:49:09,625] [INFO@aiohttp.access] 127.0.0.1 [19/Mar/2021:04:49:09 +0000] "PUT /transactions/635?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
Mar 19 00:49:09  python[28528]: [2021-03-19 00:49:09,626] [DEBUG@mau.mx] Received Matrix event $*** from @*** in !***.com
Mar 19 00:49:13  python[28528]: [2021-03-19 00:49:13,730] [INFO@aiohttp.access] 127.0.0.1 [19/Mar/2021:04:49:13 +0000] "PUT /transactions/636?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
Mar 19 00:49:42  python[28528]: [2021-03-19 00:49:42,820] [INFO@mau.user.@***com] Connected to Signal
Mar 19 00:49:43  python[28528]: [2021-03-19 00:49:43,843] [ERROR@mausignald] Failed to handle incoming request {"id":"***","type":"get_profile","error":{},"error_type":"RequestProcessingError"}
Mar 19 00:49:43  python[28528]: Traceback (most recent call last):
Mar 19 00:49:43  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 160, in _read_loop
Mar 19 00:49:43  python[28528]:     await self._handle_incoming_line(line_str)
Mar 19 00:49:43  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 141, in _handle_incoming_line
Mar 19 00:49:43  python[28528]:     self._run_response_handlers(UUID(req_id), req_type, req)
Mar 19 00:49:43  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/rpc.py", line 119, in _run_response_handlers
Mar 19 00:49:43  python[28528]:     waiter.set_exception(make_response_error(req["error"]))
Mar 19 00:49:43  python[28528]:   File "/usr/lib/python3.9/site-packages/mausignald/errors.py", line 64, in make_response_error
Mar 19 00:49:43  python[28528]:     return response_error_types.get(data["type"], ResponseError)(data)
Mar 19 00:49:43  python[28528]: KeyError: 'type'
Mar 19 00:49:43  python[28528]: [2021-03-19 00:49:43,969] [INFO@aiohttp.access] 127.0.0.1 [19/Mar/2021:04:49:43 +0000] "PUT /transactions/637?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
Mar 19 00:49:44  python[28528]: [2021-03-19 00:49:44,896] [INFO@aiohttp.access] 127.0.0.1 [19/Mar/2021:04:49:44 +0000] "PUT /transactions/638?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
Mar 19 00:51:05  python[28528]: [2021-03-19 00:51:05,940] [INFO@aiohttp.access] 127.0.0.1 [19/Mar/2021:04:51:05 +0000] "PUT /transactions/639?access_token=*** HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
Mar 19 00:51:05  python[28528]: [2021-03-19 00:51:05,941] [DEBUG@mau.mx] Received Matrix event $-v*** from @***.com in !n***com
Mar 19 00:51:06  python[28528]: [2021-03-19 00:51:06,343] [ERROR@mausignald] Failed to handle incoming request {"id":"***different","type":"get_profile","error":{},"error_type":"RequestProcessingError"}
```
etc.

```
Mar 19 00:49:21  signald[28480]: 00:49:21.985 [socketlistener] INFO  manager-************ - Created a manager for ************
Mar 19 00:49:43  signald[28480]: 00:49:43.842 [socketlistener] ERROR get_profile - error while handling request
Mar 19 00:49:43  signald[28480]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
Mar 19 00:49:43  signald[28480]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:49:43  signald[28480]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:49:43  signald[28480]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:49:43  signald[28480]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
Mar 19 00:49:43  signald[28480]:         at io.finn.signald.clientprotocol.v1.GetProfileRequest.run(GetProfileRequest.java:65) ~[signald.jar:unspecified]
Mar 19 00:49:43  signald[28480]:         at io.finn.signald.clientprotocol.v1.GetProfileRequest.run(GetProfileRequest.java:34) ~[signald.jar:unspecified]
Mar 19 00:49:43  signald[28480]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:150) [signald.jar:unspecified]
Mar 19 00:49:43  signald[28480]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
Mar 19 00:49:43  signald[28480]:         at java.lang.Thread.run(Thread.java:832) [?:?]
Mar 19 00:49:43  signald[28480]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
Mar 19 00:49:43  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:49:43  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:49:43  signald[28480]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-armv7-unknown-linux-gnueabihf-2.15.3_unofficial_19.jar:?]
Mar 19 00:49:43  signald[28480]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
Mar 19 00:49:43  signald[28480]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
Mar 19 00:49:43  signald[28480]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
Mar 19 00:49:43  signald[28480]:         ... 1 more
Mar 19 00:50:22  signald[28480]: Mar 19, 2021 12:50:22 AM okhttp3.internal.platform.Platform log
Mar 19 00:50:22  signald[28480]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Mar 19 00:50:28  signald[28480]: Mar 19, 2021 12:50:28 AM okhttp3.internal.platform.Platform log
Mar 19 00:50:28  signald[28480]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Mar 19 00:51:06  signald[28480]: 00:51:06.342 [socketlistener] ERROR get_profile - error while handling request
Mar 19 00:51:06  signald[28480]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
```
etc.

PS: `signaldctl` arm build link is broken.

**Comment by podiki** [comment]
> I was able to replicate the garbled profile name issue and filed https://gitlab.com/signald/signald/-/issues/145

Perhaps a change on Signal's end? If this is all on signald side I can move over to an issue there, though hopefully if you can reproduce that will give me confidence it's not just something I did. I can also start from scratch to test (though in the morning, late here).

**Comment by thefinn93** [comment]
this definitely looks like a bug with linking in signald, I'm going to dig into it. I highly doubt the change was on Signal's end.

**Comment by thefinn93** [comment]
Found and fixed the garbled profile name issue.

**Comment by felixx9** [comment]
What I did after having the error, described in #70:
OS: Ubuntu 20.04
- uninstall signald
- delete /var/lib/signald
- new install master branch ()

seems to work.
when I create a room with pm +01234567 I got an error and I only see phone number, not profile name:
```

[2021-03-22 10:09:38,544] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix/appservice/as_handler.py", line 178, in try_handle
    await handler_func(event)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 444, in int_handle_event
    await self.handle_join(evt.room_id, UserID(evt.state_key), evt.event_id)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/matrix.py", line 80, in handle_join
    await portal.handle_matrix_join(user)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 279, in handle_matrix_join
    await self.update_info(user, GroupV2ID(id=self.chat_id))
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 625, in update_info
    raise ValueError(f"Unexpected type for direct chat update_info: {type(info)}")
ValueError: Unexpected type for direct chat update_info: <class 'mausignald.types.GroupV2ID'>
```

But after run "sync" in signalbot room, it looks fine for now.

**Comment by tulir** [comment]
That exception is fixed by e1baef535a84be26fb8ff5aa8ae3d7eca96d2961

**Comment by felixx9** [comment]
perfect. Does not happen anymore (after update). Because it's fixed (hopefully) or because I did the sync before ;)

**Comment by podiki** [comment]
Doing the same thing as @felixx9 and removing all of signald has everything working again. I thought deleting signald's db and user info should have done the same thing, but something wasn't cooperating.

I'm not sure then if this is fixed? The unencrypted names may have caused this, or at least was the start for me (and then my trying to update/fix things...). And with that now gone I guess we're good...?

**Comment by podiki** [comment]
Looks like same issue under different circumstances (not the user name decryption) in #81, so perhaps this is a wider problem? Or something for upstream signald?
