### ISSUE TITLE
Cannot re-link: KeyError: 'type'

### ISSUE THREAD

**Issue by felixx9** [tulir/mautrix-signal#70]
Had some trouble last days after

1. one user had a new device
2. updating singnald / mautrix-signal

I got room with crazy long hyroglyphic names. I left my signalbot room an now, when re-establish the connection

1. invite signalbot
2. link <devicename>

generates this error

```
[2021-03-19 10:37:41,988] [ERROR@mausignald] Failed to handle incoming request {"id":"81e25b25-3216-415e-8819-ffac3ac2c8bf","type":"finish_link","error":{},"error_type":"RequestProcessingError"}
Traceback (most recent call last):
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 160, in _read_loop
    await self._handle_incoming_line(line_str)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 141, in _handle_incoming_line
    self._run_response_handlers(UUID(req_id), req_type, req)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 119, in _run_response_handlers
    waiter.set_exception(make_response_error(req["error"]))
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/errors.py", line 64, in make_response_error
    return response_error_types.get(data["type"], ResponseError)(data)
KeyError: 'type'

```

1. pm +123455677899 creates this response:
`This command requires you to be logged in.`

not sure, whtether this coud be mautrix-signal or signald related

**Comment by podiki** [comment]
This looks the same (or same realm) as #69; the profile name issue is in signald and should be fixed at least now, but still working out the linking error. Probably we should follow up directly with signald.

**Comment by felixx9** [comment]
yes - seems to be same... thx!
