### ISSUE TITLE
SerializerError on register

### ISSUE THREAD

**Issue by abliss** [tulir/mautrix-signal#72]
After typing my verification code to the bot (0.1.0+dev.[8738afa3], installed via ansible) i get:

Unhandled error while handling command:

```traceback
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 131, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 3 required positional arguments: 'account_id', 'device_id', and 'address'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 108, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 110, in verify
    return Account.deserialize(resp)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 297, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 137, in _dict_to_attrs
    raise SerializerError("Missing value for required key "
mautrix.types.util.serializable.SerializerError: Missing value for required key account_id in Account
```

**Comment by rjmidau** [comment]
It looks like mautrix-signal was updated in 8738afa35a8bfc694e9e927acaf5eb9f7eae9e46 to expect signald to return [v1/account](https://docs.signald.org/protocol/structures/v1/Account/) when sent a [v1/verify](https://docs.signald.org/protocol/actions/v1/verify/) (as per the signald docs), but signald does not [default](https://github.com/thefinn93/signald/blob/5dbcc5393563e15a94ca98b497f925003d6151af/src/main/java/io/finn/signald/clientprotocol/Request.java#L76) to its v1 response for v1/verify currently, and has to be [explicitly requested](https://github.com/thefinn93/signald/blob/5dbcc5393563e15a94ca98b497f925003d6151af/src/main/java/io/finn/signald/clientprotocol/Request.java#L113) by setting the "version" attribute to "v1" in the request payload. Without this, the code will return a [v0/JsonAccount](https://docs.signald.org/protocol/structures/v0/JsonAccount/) response.
