### ISSUE TITLE
Duplicate puppet uuid error

### ISSUE THREAD

**Issue by theCalcaholic** [tulir/mautrix-signal#82]
My Signal bridge stopped working, presumable because of the following error:

```
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "puppet_uuid_key"
```

Any idea on how to fix it?

Full error log:

```
Apr 06 10:51:50 <hostname> matrix-mautrix-signal[11699]: [2021-04-06 08:51:50,436] [INFO@mau.init] Startup actions complete in 0.17 seconds, now running forever
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]: [2021-04-06 08:51:57,277] [ERROR@mau.portal.wdsCWeapoAIoatU+NSnlB7AfaasaVgTH5xb/ge7/g=] Failed to update por
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]: Traceback (most recent call last):
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 823, in update_matrix_room
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await self._update_matrix_room(source, info)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 860, in _update_matrix_room
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await self.update_info(source, info)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 659, in update_info
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await self._update_participants(source, info)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 753, in _update_participants
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     puppet = await p.Puppet.get_by_address(address)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix/bridge/async_getter_lock.py", line 14, in wrapper
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     return await fn(cls, *args, **kwargs)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/puppet.py", line 333, in get_by_address
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await puppet.handle_uuid_receive(address.uuid)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/puppet.py", line 124, in handle_uuid_receive
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await self._handle_uuid_receive(uuid)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/puppet.py", line 133, in _handle_uuid_receive
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await self._set_uuid(uuid)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/db/puppet.py", line 69, in _set_uuid
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     await conn.execute("UPDATE puppet SET uuid=$1 WHERE number=$2", uuid, self.number)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/asyncpg/connection.py", line 297, in execute
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     _, status, _ = await self._execute(query, args, 0, timeout, True)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/asyncpg/connection.py", line 1445, in _execute
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     result, _ = await self.__execute(
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/asyncpg/connection.py", line 1454, in __execute
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     return await self._do_execute(query, executor, timeout)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "/usr/lib/python3.8/site-packages/asyncpg/connection.py", line 1476, in _do_execute
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:     result = await executor(stmt, None)
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]:   File "asyncpg/protocol/protocol.pyx", line 196, in bind_execute
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]: asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "puppet_uuid_key"
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]: DETAIL:  Key (uuid)=(e78asaac-dac0-429b-85d0-6a879b9eeb2c) already exists.
Apr 06 10:51:57 <hostname> matrix-mautrix-signal[11699]: [2021-04-06 08:51:57,368] [INFO@aiohttp.access] 172.25.0.15 [06/Apr/2021:08:51:57 +0000] "PUT /transactions/14
Apr 06 10:51:58 <hostname> matrix-mautrix-signal[11699]: [2021-04-06 08:51:58,860] [INFO@aiohttp.access] 172.25.0.15 [06/Apr/2021:08:51:58 +0000] "PUT /transactions/14
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]: [2021-04-06 08:52:00,470] [ERROR@mausignald] Failed to handle incoming request {"id":"57c03f13-8c88-4696-bf9b-
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]: Traceback (most recent call last):
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 160, in _read_loop
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:     await self._handle_incoming_line(line_str)
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 141, in _handle_incoming_line
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:     self._run_response_handlers(UUID(req_id), req_type, req)
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 119, in _run_response_handlers
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:     waiter.set_exception(make_response_error(req["error"]))
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:   File "/opt/mautrix-signal/mausignald/errors.py", line 64, in make_response_error
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]:     return response_error_types.get(data["type"], ResponseError)(data)
Apr 06 10:52:00 <hostname> matrix-mautrix-signal[11699]: KeyError: 'type'
```

**Comment by disambiguator** [comment]
@theCalcaholic You still seeing this? my bridge has been completely broken this week as well.
