### ISSUE TITLE
Authorization failed exception

### ISSUE THREAD

**Issue by seanfarley** [tulir/mautrix-signal#86]
Seemingly randomly (starting May 1st, ~10 days ago), the signal matrix bridge stopped working. Upon further inspection, there are many authorization errors (full stack trace below). I've tried unlinking and re-linking but to no success. Seems very similar to #69.

<details>
May 11 20:19:34 farley.io matrix-mautrix-signal-daemon[6797]: 20:19:34.666 [socketlistener] INFO  io.finn.signald.MessageReceiver - Last client for **********27 unsubscribed, shutting down message pipe!
May 11 20:20:18 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:18.862 [socketlistener] INFO  manager-**********27 - Created a manager for **********27
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:23.065 [socketlistener] WARN  io.finn.signald.clientprotocol.v1.ListContactsRequest - error refreshing profile:
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:60) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:36) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at java.lang.Thread.run(Unknown Source) [?:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         ... 1 more
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:23.634 [socketlistener] WARN  io.finn.signald.clientprotocol.v1.ListContactsRequest - error refreshing profile:
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:60) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:36) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at java.lang.Thread.run(Unknown Source) [?:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
May 11 20:20:23 farley.io matrix-mautrix-signal-daemon[6797]:         ... 1 more
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:24.236 [socketlistener] WARN  io.finn.signald.clientprotocol.v1.ListContactsRequest - error refreshing profile:
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:60) [signald.jar:unspecified]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:36) [signald.jar:unspecified]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at java.lang.Thread.run(Unknown Source) [?:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
May 11 20:20:24 farley.io matrix-mautrix-signal-daemon[6797]:         ... 1 more
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:42.989 [socketlistener] WARN  io.finn.signald.clientprotocol.v1.ListContactsRequest - error refreshing profile:
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:60) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:36) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at java.lang.Thread.run(Unknown Source) [?:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         ... 1 more
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:43.564 [socketlistener] WARN  io.finn.signald.clientprotocol.v1.ListContactsRequest - error refreshing profile:
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:60) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:36) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at java.lang.Thread.run(Unknown Source) [?:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
May 11 20:20:43 farley.io matrix-mautrix-signal-daemon[6797]:         ... 1 more
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]: 20:20:44.133 [socketlistener] WARN  io.finn.signald.clientprotocol.v1.ListContactsRequest - error refreshing profile:
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:70) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.SettableFuture.get(SettableFuture.java:85) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.util.concurrent.FutureMapTransformer.get(FutureMapTransformer.java:66) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.jobs.RefreshProfileJob.run(RefreshProfileJob.java:69) ~[signald.jar:unspecified]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:60) [signald.jar:unspecified]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:36) [signald.jar:unspecified]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at java.lang.Thread.run(Unknown Source) [?:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]: Caused by: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.access$500(PushServiceSocket.java:163) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket$4.onResponse(PushServiceSocket.java:1420) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) ~[okhttp-4.6.0.jar:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
May 11 20:20:44 farley.io matrix-mautrix-signal-daemon[6797]:         ... 1 more
</details>

**Comment by seanfarley** [comment]
To others that might find this issue, I "fixed" this by deleting the docker images and cache on disk (well, moved to another location, just for backup) located in `{{ matrix_base_data_path }}/matrix-signal`. Hope that helps someone else!
