### ISSUE TITLE
Failed to sync contact: UnexpectedError: javax.crypto.AEADBadTagException: Tag mismatch!

### ISSUE THREAD

**Issue by markusressel** [tulir/mautrix-signal#9]
Hi there,

installed and configured mautrix-signal today using the docker method (inside a rancher managed kubernetes).
Most things seem to work fine, however I get this error message in the logs:

```
[2020-11-04 02:49:35,243] [ERROR@mau.user.@markus:redacted.de] Failed to sync contact Address(number='+49READACTED', uuid=UUID('READACTED'))
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_signal/user.py", line 123, in _sync
    await self._sync_contact(contact, create_contact_portal)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/user.py", line 99, in _sync_contact
    profile = await self.bridge.signal.get_profile(self.username, contact.address)
  File "/opt/mautrix-signal/mausignald/signald.py", line 138, in get_profile
    resp = await self.request("get_profile", "profile", username=username,
  File "/opt/mautrix-signal/mausignald/rpc.py", line 157, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 154, in _raw_request
    return await future
mausignald.errors.UnexpectedError: javax.crypto.AEADBadTagException: Tag mismatch!
```

Any idea what this means and how I can fix it?

**Comment by Legogris** [comment]
Getting this too

**Comment by thefinn93** [comment]
This is a signald issue. It's an error that occurs while decrypting profiles sometimes. If you're still experiencing it on the latest signald, please report it here: https://gitlab.com/signald/signald/-/issues/new

**Comment by markusressel** [comment]
Thx for the info, I will close this as I have not Seen this error in a while.
